### PR TITLE
[CodeCamp2023-473] Add a text translation example

### PR DESCRIPTION
**Pull request by Desjajja**
## Motivation

One of Openmmlab codecamp task.

## Modification

Added a example script training a [t5-small](https://huggingface.co/t5-small) model on [opus books, a multi-language text translation dataset](https://huggingface.co/t5-small). Default task is to translate English text to French, which is configurable from line 67 to 69, and line 92.

## Checklist

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.

_No other code is altered, hence I didn't go through unit tests or add docs._

### CODE REVIEW

**Comment by Desjajja** [comment]
Sure. This log records a training course of two epochs and two validation phases. The loss is generated by t5-small model during training, and bleu-score is used in validation stage.



Don’t hesitate to contact me if you need any more information. 

 

P.S. I am not sure if you want the weight file, but I attached a screenshot of it in the workdir as a proof. 

 

发件人: ***@***.*** ***@***.***> 代表 Zaida Zhou
发送时间: Wednesday, August 2, 2023 7:01 PM
收件人: open-mmlab/mmengine ***@***.***>
抄送: Desjajja ***@***.***>; Mention ***@***.***>
主题: Re: [open-mmlab/mmengine] [CodeCamp2023-473] Add a text translation example (PR #1283)

 

Hi @Desjajja <https://github.com/Desjajja>  , thanks for your contribution. Could you provide the training logs?

**Comment by Desjajja** [comment]
> Hi @Desjajja , thanks for your contribution. Could you provide the training logs?

Sure.

[20230731_081824.log](https://github.com/open-mmlab/mmengine/files/12246365/20230731_081824.log)

**Comment by zhouzaida** [comment]
Hi, does the `bleu_score: 0.0486` in the log match the expected result?

**Comment by Desjajja** [comment]
> Hi, does the `bleu_score: 0.0486` in the log match the expected result?

No, I expected it to be at least 0.4 or something. However, since bleu score is intended for [corpus-level tasks](https://github.com/mjpost/sacrebleu/issues/98#issuecomment-659503979) and I computed the metric between sentence pairs, it is reasonable to witness this outcome.
```python
decoded_preds = [pred.split() for pred in preds]   # translation text split into sequence of tokens
decoded_labels = [[label.split()] for label in labels] # reference corpus where only one sentence is provided
score = bleu_score(decoded_preds, decoded_labels) # hence the score could be quite low
```
Maybe the decrease in loss shows a more promising result. And I am planning to add[ sentence-level bleu](https://github.com/mjpost/sacrebleu#compatibility-api) if available.

**Comment by zhouzaida** [comment]
Got it.

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
