### PR TITLE
[Fix] Fix open() encoding problem of Config in Windows

### PR DESCRIPTION
**Pull request by sanbuphy**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
fix the issue
#647 
## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by HAOCHENYE** [comment]
@zhouzaida Should we force using utf-8 to decode the config file?

**Comment by ZwwWayne** [comment]
We should do that, it has been done in other places actually.

**Review by HAOCHENYE — APPROVED** [review]

**Review by zhouzaida — APPROVED** [review]

**Comment by HAOCHENYE** [comment]
@sanbuphy 

https://github.com/open-mmlab/mmengine/blob/6178ef25b04b931e2493115fe07bace9e90dd652/mmengine/config/config.py#L421

https://github.com/open-mmlab/mmengine/blob/6178ef25b04b931e2493115fe07bace9e90dd652/mmengine/config/config.py#L553

These lines should also be refined.

**Comment by sanbuphy** [comment]
> @sanbuphy
> 
> https://github.com/open-mmlab/mmengine/blob/6178ef25b04b931e2493115fe07bace9e90dd652/mmengine/config/config.py#L421
> 
> https://github.com/open-mmlab/mmengine/blob/6178ef25b04b931e2493115fe07bace9e90dd652/mmengine/config/config.py#L553
> 
> These lines should also be refined.

OK, I create a PR #653

**Pull request merged**
