### PR TITLE
[Fix] Delete frozen parameters when using `paramwise_cfg`

### PR DESCRIPTION
**Pull request by LZHgrla**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers. By the way, if you're not familiar with how to use pre-commit to fix lint issues or add unit tests, please refer to [Contributing to OpenMMLab](https://mmengine.readthedocs.io/en/latest/notes/contributing.html).

## Motivation

It will cause errors when initializing DeepSpeed optimizer, with
1. Freezing some parameters of the model
2. Setting `paramwise_cfg` for optimizer to set different lr or weight_decay for different parameters

This is because that if setting `paramwise_cfg`, mmengine will treat each parameter (including frozen parameters) as a separate group, and that will lead to an empty list of `trainable_parameters` on the below code.

https://github.com/microsoft/DeepSpeed/blob/2afa1c7f2f961ef18042a88467ff5d3373c22c07/deepspeed/runtime/zero/stage_1_and_2.py#L308-L313

## Modification

`mmengine/_strategy/deepspeed.py`

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
4. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMPretrain.
5. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by SCZwangxiao** [comment]
I think this solution only works for ZeRO-1

**Comment by zhouzaida** [comment]
How about moving this logic deleting frozen parameters to `DefaultOptimWrapperConstructor`. 

https://github.com/open-mmlab/mmengine/blob/ba5eed8409d51a7af608ec3d1a300f1dd352906b/mmengine/optim/optimizer/default_constructor.py#L206-L267

**Comment by LZHgrla** [comment]
> How about moving this logic deleting frozen parameters to `DefaultOptimWrapperConstructor`.
> 
> https://github.com/open-mmlab/mmengine/blob/ba5eed8409d51a7af608ec3d1a300f1dd352906b/mmengine/optim/optimizer/default_constructor.py#L206-L267

Good idea!

Shall we delete these codes?

https://github.com/open-mmlab/mmengine/blob/ba5eed8409d51a7af608ec3d1a300f1dd352906b/mmengine/optim/optimizer/default_constructor.py#L215-L217

**Comment by zhouzaida** [comment]
Yes, we can delete it.

> > How about moving this logic deleting frozen parameters to `DefaultOptimWrapperConstructor`.
> > https://github.com/open-mmlab/mmengine/blob/ba5eed8409d51a7af608ec3d1a300f1dd352906b/mmengine/optim/optimizer/default_constructor.py#L206-L267
> 
> Good idea!
> 
> Shall we delete the L216?
> 
> https://github.com/open-mmlab/mmengine/blob/ba5eed8409d51a7af608ec3d1a300f1dd352906b/mmengine/optim/optimizer/default_constructor.py#L215-L217

**Comment by LZHgrla** [comment]
Hi, @zhouzaida 
I have fixed it!
Ready for review and merge.

**Comment by zhouzaida** [comment]
> Hi, @zhouzaida I have fixed it! Ready for review and merge.

Please fix the ut.

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
